[ids]
*

[main]
# Tap Caps Lock -> Escape.  Hold Caps Lock -> the "umlaut" layer below.
capslock = overload(umlaut, esc)

[umlaut]
a = ä
e = ë
o = ö
u = ü
s = ß

[umlaut+shift]
a = Ä
e = Ë
o = Ö
u = Ü
s = ẞ
