# Managed by wallpaper-picker.sh — edit via the picker (Super + Ctrl + Space)

preload = /home/sadi/Pictures/astronaut.png
preload = /home/sadi/Pictures/samurai.jpg
preload = /home/sadi/Pictures/space.png

wallpaper = ,/home/sadi/Pictures/space.png
wallpaper = DP-1,/home/sadi/Pictures/astronaut.png
wallpaper = eDP-1,/home/sadi/Pictures/samurai.jpg

splash = false
ipc = on
