# Assign workspaces to monitors

workspace = 1, monitor:eDP-1, default:true
workspace = 3, monitor:eDP-1
workspace = 5, monitor:eDP-1

workspace = 2, monitor:DP-1, default:true
workspace = 4, monitor:DP-1
workspace = 6, monitor:DP-1

# Window rules (0.53+ syntax)
windowrule = workspace 1 silent, match:class zen
windowrule = workspace 2 silent, match:class Alacritty
windowrule = workspace 5 silent, match:class discord
windowrule = workspace 6 silent, match:class Anki
